'''import greetings

greetings.greet()
greetings.greetName("Rakesh")
# greetings.prep_greeting
'''

# from greetings import greet, greetName
# from greetings import *
# import greetings

# greet()
# greetings.prep_greeting

# greetings.greet()


###############################################################################


# from math.algebra import add, div
# import math.algebra as al

# al.add(1, 2)


# print(add(1, 2))
# print(div(14, 7))

# from mymath import *

# print(add(1, 2))

# from mymath.algebra.simultaneous import someMethod
from mymath import *
# from mymath.algebra import helper
# from mymath.algebra import * 
# from mymath.log import * 

print(add(1, 2))
# helper()
# greet()
# PrintLine("#")

import mymath.algebra

print(algebra.add(2, 3))


def Test1():
    from mymath import add
    print(add(1, 2))

    # from mymath import *  # ERROR inside a local scope; Only possible in global 
    
